name: ubuntu_trigger
on: [repository_dispatch]
jobs:
  build-on-remote-trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag detallado/ubuntu
    - name: Push the image to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin && docker push detallado/ubuntu
